services:
  postgres:
    image: postgres:latest
    container_name: customer-service
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: customers-ecommerce-app
    ports:
      - "5438:5432"
    volumes:
      - my_postgres_data:/var/lib/postgresql/data

volumes:
  my_postgres_data: