server:
  port: 8090

spring:
  datasource:
    url: jdbc:postgresql://localhost:5438/customers-ecommerce-app
    username: admin
    password: secret
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect